Message.create!(user_id: 1, content: 'おはよう')
Message.create!(user_id: 2, content: 'こんにちは')
Message.create!(user_id: 1, content: 'こんばんは')
Message.create!(user_id: 3, content: 'テスト')
Message.create!(user_id: 1, content: 'おやすみ')
